name: Convert XML to JSON

on:
  push:
    branches:
      - main

jobs:
  convert-xml-to-json:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y xmlstarlet

      - name: Download XML file
        run: |
          curl -o cyberattacks_news.xml https://raw.githubusercontent.com/Casualtek/Cyberwatch/main/cyberattacks_news.xml

      - name: Convert XML to JSON
        run: |
          xmlstarlet sel -t -m "//item" -v "title" -o "[SEP]" -v "guid" -o '[SEP]' -v "pubDate" -n cyberattacks_news.xml | node -e "const readline = require('readline'); const rl = readline.createInterface({ input: process.stdin, output: process.stdout, terminal: false }); let result = []; rl.on('line', line => {   const [title, link, date] = line.split('[SEP]').slice(0, 3);  result.push({ title: String(title).trim(), link: String(link).trim(), date:new Date( String(date).trim()).toISOString() }); });rl.on('close', () => {  console.log(JSON.stringify(result, null, 2));});" > output.json
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output.json
          git commit -m "Convert XML to JSON"
          git push
